# Generated by Django 4.2.1 on 2023-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otgul',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='otpusk',
            name='end_date',
            field=models.DateField(verbose_name='Конец отпуска'),
        ),
        migrations.AlterField(
            model_name='otpusk',
            name='start_date',
            field=models.DateField(verbose_name='Начало отпуска'),
        ),
    ]
