# Generated by Django 4.2.1 on 2023-06-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_otkaz_remove_otgul_odobreno_remove_otpusk_odobreno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otgul',
            options={'ordering': ['-created_date', '-edit_date'], 'verbose_name': 'Заявка на отгул', 'verbose_name_plural': 'Заявки на отгул'},
        ),
        migrations.AlterModelOptions(
            name='otpusk',
            options={'ordering': ['-created_date', '-edit_date'], 'verbose_name': 'Заявка на отпуск', 'verbose_name_plural': 'Заявки на отпуск'},
        ),
    ]
